[package]
name = "sysinfobar"
version = "0.1.1"
authors = ["nakal <nakal@users.noreply.github.com>"]

[dependencies]
libc = { version = "0.2.148" }
chrono = { version = "0.4.31", features = ["unstable-locales"] }
